In [1]:
import numpy as np

**numerical python即numpy库提供N维数组这个数据结构：ND array.**<br>
numpy的数组与python内置列表都可以:1.下标进行索引2.切片操作3.for迭代<br>但是numpy数组内数据类型必须一致而列表无需，numpy数组中的数据运算效率更高并提供计算标准差等多种数据处理的函数

**创建n维数组(几个方括号就是几维数组)**

In [2]:
arr1 = np.array([1,2,3])

In [3]:
arr1

array([1, 2, 3])

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

**shape返回一个元组告诉你数组中：1维数组中一行有几列，列数作为唯一元素显示在元组中也要加,！ 2维数组中有几行几列 3维数组中深度（Z轴）多少几行几列**

In [6]:
print(arr1.shape)

(3,)


In [7]:
print(arr2.shape)

(2, 3)


**nidm告诉你数组的维度**

In [8]:
print(arr1.ndim)

1


In [9]:
print(arr2.ndim)

2


**dtype告诉你数组中数据的类型**

In [10]:
print(arr2.dtype)

int64


**除了手动创建数组还可以 ones zeros arange创建数组，要注意括号层数(只要你想创建的数组超过一维，第一个参数就必须是一个元组！)！！**

*创建一维(一行几列)与二维（几行几列）全1数组，默认浮点型*

In [11]:
print(np.ones(4))

[1. 1. 1. 1.]


In [12]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


*创建一维与二维（几行几列）全0数组，默认浮点型*

In [13]:
print(np.zeros(4))

[0. 0. 0. 0.]


In [14]:
print(np.zeros((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


*创建等差数组(左闭右开)与步长*

In [15]:
print(np.arange(5,11,2))

[5 7 9]


In [16]:
print(np.arange(5,8,0.5))

[5.  5.5 6.  6.5 7.  7.5]


# Numpy-数组array练习

必须把import部分代码给他运行成功之后下面对numpy的使用才不会报错

In [17]:
import numpy as np

**创建一个变量名为 arr1 的一维数组，里面的元素为整数6、2、-7、2、8、-2、1。创建后输出 arr1。**
*注意：同意单元格内各行交互式指令都会执行但只会显示最后一行指令,要想全部显示则需print*

In [18]:
arr1 = np.array([6,2,-7,2,8,-2,1])
a = 3
a
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

**创建一个变量名为 arr2 的二维数组，里面的元素为以下两个数组：由整数1、3、5组成的一维数组，以及由整数2、4、6组成的一维数组。创建后输出 arr2**

In [19]:
arr2 = np.array([[1,3,5],[2,4,6]])
a=3
print(a)
arr2

3


array([[1, 3, 5],
       [2, 4, 6]])

**分别打印 arr1 和 arr2 的维度、形状（显示为元组，元组中单个元素也要加,）、元素数量、元素类型。**

In [20]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(7,)
(2, 3)
7
6
int64
int64


**创建一个变量名为 arr_all_0 的一维数组，里面的元素为6个0，并输出。**

In [21]:
arr_all_0 = np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

**创建一个变量名为 arr_all_1 的一维数组，里面的元素为6个1，并输出数字后有.表示为浮点型**

In [22]:
arr_all_1 = np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

**创建一个变量名为 arr_even 的一维数组，里面的元素为10（包括10）到20（包括20）之间的偶数，并输出。**

In [23]:
arr_even = np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])

# array数组的操作

## 数组连接 np.concatenate

In [24]:
import numpy as np
arr1 = np.array([2,3,4,5])
arr2 = np.zeros(2)
arr3 = np.ones(3)

*因为数组中数据类型必须统一故整数数组+浮点型数组为浮点型数组*

In [25]:
print(np.concatenate([arr1,arr2,arr3]))

[2. 3. 4. 5. 0. 0. 1. 1. 1.]


## 数组的排序 

np.sort(arr)不改变数组-列表中sorted(list)  arr.sort()改变数组-列表中list.sort()

In [26]:
arr = np.array([2,5,1,9,7,-4])
print(np.sort(arr))
arr

[-4  1  2  5  7  9]


array([ 2,  5,  1,  9,  7, -4])

In [27]:
arr.sort()
arr

array([-4,  1,  2,  5,  7,  9])

## 数组索引

In [28]:
arr3 = np.array([3,34,56,74,4]) 

*注意在jupyter中写代码时如果数组的定义与数组的操作不在同一个单元格内时候一定要把数组定义的那个单元格先运行后再去运行数组操作的那个单元格否则nameerror*
<br>此外如果在jupyter中出现两个同名的数组，你之前用arr3命名过np.ones(3)并且运行过它，你忘记在运行这里的arr3去覆盖原先数据那么下面的操作对象将会是上面的arr3，产生索引错误,同样当你覆盖掉原先的arr3后你在去执行原先相配套操作后操作，对象就又不同了

In [29]:
print(arr3[0])
print(arr3[4])
print(arr3[-1])
print(arr3[-2])

3
4
4
74


数组切片[a:b]:数组的第a+1个元素到第b个元素（依旧左闭右开）

In [30]:
print(arr3[0:5])

[ 3 34 56 74  4]


## 数组运算

*这样定义数组是错误的，你定义的是列表而非数组！！*

In [31]:
arr1 = [1,2,3]
arr2 = [1,1,1]

In [32]:
print(arr1+arr2)

[1, 2, 3, 1, 1, 1]


In [33]:
arr1+arr2

[1, 2, 3, 1, 1, 1]

In [34]:
print(arr1 * 10)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [35]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

AttributeError: 'list' object has no attribute 'max'

*下面的定义数组方法才是对的，很明显的区别就是相同操作不同结果且数组部分操作不可用于列表会报上述错！！！*

In [36]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,1,1])

In [37]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]


In [38]:
print(arr1*10)

[10 20 30]


In [39]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

3
1
6
2.0


## 筛选数组的值

注意在jupyter中你定义完一个对象最好在同一个单元格内定义相关操作可保证操作与对象一致，若操作，对象在不同单元格那么一定要记得先运行定义对象后再运行操作，否则会报未定义对象错误/有多个同名对象时会报操作错误

In [40]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1[arr1>4.5]

array([5, 6, 7])

*python中的 and or not 对应数组中的 & | ~*

In [41]:
arr1[(arr1>3) & (arr1<6)]

array([4, 5])